//because windows sucks...

#ifndef FILTERDIRECTORYQTSO_CROSSPLATFORMMACROS_HPP
#define FILTERDIRECTORYQTSO_CROSSPLATFORMMACROS_HPP

#include <QtCore/QtGlobal>

//remember to define this variable in the .pro file
#if defined(FILTERDIRECTORYQTSO_LIBRARY)
#  define EXPIMP_FILTERDIRECTORYQTSO Q_DECL_EXPORT
#else
#  define EXPIMP_FILTERDIRECTORYQTSO Q_DECL_IMPORT
#endif

#endif // FILTERDIRECTORYQTSO_CROSSPLATFORMMACROS_HPP
